### PR TITLE
Adding no range option for prometheus queries

### PR DESCRIPTION
**Pull request by paigerube14**
For critical alerts, dont want to look at any past alerts that were firing; want just at the current moment. Adding this as an option with the same funciton

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by shahsahil264 — APPROVED** [review]
/lgtm

**Comment by paigerube14** [comment]
@tsebastiani are we ok to merge without the tests passing, the prometheus tests (what I changed) are passing
The failed tests dont seem like they should be effected by my changes. Thoughts?

**Comment by tsebastiani** [comment]
Lgtm

**Pull request merged**
